let score = 33;

console.log(typeof score);
console.log(typeof score);

//checking numbers
let score2 = "33ab";

console.log(typeof score2);

let valueInNumber = Number(score2);
console.log(typeof valueInNumber);
console.log(valueInNumber);

//"33" => 33
//"33abc" => NAN
//true => 1; false => 0
//null => 0
//undefined => NAN
//"" => 0

let isLoggedIn = 1;
let booleanIsLoggedIn = Boolean(isLoggedIn);

console.log(booleanIsLoggedIn);
// "ujval" => true
// "" => false
// 0 => false
// 1 => true
// null => false

//prefix and postfix operators need to read it from the mdn documensts
